Import( 'project' )
Import( 'libs' )

project.StaticLibrary( 'mvp_player_core',
                       sources   = project.scanFiles( ['src'] ),
                       includes  = ['src'],
                       libraries = [
                                     libs.boost,
                                     libs.boost_filesystem,
                                     libs.boost_chrono,
                                     libs.boost_thread,
                                     libs.fmod,
                                    ],
                       shared = False
                      )

