Import( 'project' )
Import( 'libs' )

sourcesDir = 'src'
mvpPlayerSourcesUi = project.scanFiles( sourcesDir, accept=['*.ui'] )

project.StaticLibrary( 'mvp_player_qtgui',
                       sources   = project.scanFiles( ['src'] ),
                       includes  = ['src'],
                       libraries = [
                                     libs.boost,
                                     libs.qt5( modules=[ 'QtCore', 'QtGui', 'QtWidgets', 'QtMultimedia' ], uiFiles=mvpPlayerSourcesUi ),
                                     libs.mvp_player_gui,
                                     libs.mvp_player_net,
                                    ],
                       shared = False
                      )
