Import( 'project' )
Import( 'libs' )

project.SharedLibrary( 'mvp_player_pluger',
                       sources   = project.scanFiles( ['src'] ),
                       includes  = ['src'],
                       libraries = [
                                     libs.mvp_player_core,
                                     libs.mvp_player_gui,
                                     libs.boostAdds,
                                     libs.qt5( modules=[ 'QtCore' ] ),
                                    ],
                      )

