Import( 'project' )
Import( 'libs' )

sourcesDir = 'src'

project.SharedLibrary( 'mvp_player_gui',
                   sources   = project.scanFiles( ['src'] ),
                   includes  = ['src'],
                   libraries = [
                                 libs.mvp_player_core,
                                ],
                  )
