Import( 'project' )
Import( 'libs' )

project.SharedLibrary( 'mvp_player_fmod',
                       sources   = project.scanFiles( ['src'] ),
                       includes  = ['src'],
                       libraries = [
                                     libs.mvp_player_core,
                                     libs.fmod,
                                    ],
                      )
