Import( 'project' )
Import( 'libs' )

libraries = [
              libs.mvp_player_core,
              libs.mvp_player_qtgui,
              libs.boost_program_options,
              libs.qt5( modules=[ 'QtCore', 'QtGui', 'QtWidgets', 'QtPrintSupport', 'QtMultimedia' ] ),
            ]

name = project.getName()
sourcesDir = '.'
sources = project.scanFiles( [sourcesDir] )

env = project.createEnv( libraries )
env.Append( CPPPATH=sourcesDir )
mvp_player = env.Program( target=name, source=sources )

install = env.Install( project.inOutputBin(), mvp_player )
env.Alias(name, install )
env.Alias('all', install )
